[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[env]
CFLAGS_riscv64gc_unknown_none_elf = "-DRING_CORE_NOSTDLIBINC -march=rv64gc -mabi=lp64d -mcmodel=medany"
CFLAGS_loongarch64_unknown_none = "-DRING_CORE_NOSTDLIBINC"

# [target.riscv64gc-unknown-none-elf]
# rustflags = [
#     "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
# ]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tsrc/linker-riscv64.ld",
    "-C",
    "force-frame-pointers=yes",
]

[target.loongarch64-unknown-none]
rustflags = [
    "-C",
    "link-arg=-Tsrc/linker-loongarch64.ld",
    "-C",
    "force-frame-pointers=yes",
]
