// src/fs/hosts.rs

use crate::error::SysError;
use crate::fs::vfs::kstat::Kstat;
use crate::fs::*;
use crate::mm::UserBuffer;
use crate::{error::SyscallResult, fs::vfs::FileInner};
use alloc::string::String;
use alloc::sync::Arc;
use alloc::vec;
use alloc::vec::Vec;
use spin::{Mutex, MutexGuard};

/// Hosts 文件内容管理
pub struct HostsManager {
    mappings: Mutex<Vec<HostsEntry>>,
}

#[derive(Clone)]
struct HostsEntry {
    ip: String,
    hostnames: Vec<String>,
}

impl HostsManager {
    ///
    pub fn new() -> Self {
        let manager = Self {
            mappings: Mutex::new(Vec::new()),
        };
        // 加载默认配置
        manager.load_default();
        manager
    }

    fn load_default(&self) {
        let mut mappings = self.mappings.lock();
        mappings.clear();

        // IPv4 localhost
        mappings.push(HostsEntry {
            ip: "127.0.0.1".to_string(),
            hostnames: vec!["localhost".to_string(), "localhost.localdomain".to_string()],
        });

        // IPv6 localhost
        mappings.push(HostsEntry {
            ip: "::1".to_string(),
            hostnames: vec![
                "localhost".to_string(),
                "ip6-localhost".to_string(),
                "ip6-loopback".to_string(),
            ],
        });

        // 本机主机名
        mappings.push(HostsEntry {
            ip: "127.0.1.1".to_string(),
            hostnames: vec!["kairix".to_string()],
        });
    }
    ///
    pub fn lookup(&self, hostname: &str) -> Option<String> {
        let mappings = self.mappings.lock();
        for entry in mappings.iter() {
            for hn in entry.hostnames.iter() {
                if hn == hostname {
                    return Some(entry.ip.clone());
                }
            }
        }
        None
    }
    ///
    pub fn add_entry(&self, ip: &str, hostname: &str) {
        let mut mappings = self.mappings.lock();
        for entry in mappings.iter_mut() {
            if entry.ip == ip {
                if !entry.hostnames.contains(&hostname.to_string()) {
                    entry.hostnames.push(hostname.to_string());
                }
                return;
            }
        }
        mappings.push(HostsEntry {
            ip: ip.to_string(),
            hostnames: vec![hostname.to_string()],
        });
    }
    ///
    pub fn load_from_content(&self, content: &str) {
        let mut mappings = self.mappings.lock();
        mappings.clear();

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 2 {
                let ip = parts[0].to_string();
                let hostnames: Vec<String> = parts[1..].iter().map(|s| s.to_string()).collect();
                mappings.push(HostsEntry { ip, hostnames });
            }
        }
    }
    ///
    pub fn get_content(&self) -> String {
        let mappings = self.mappings.lock();
        let mut content = String::new();
        content.push_str("# /etc/hosts\n");
        content.push_str("# This file is auto-generated by Kairix OS\n");
        content.push_str("#\n");

        for entry in mappings.iter() {
            content.push_str(&entry.ip);
            for hn in entry.hostnames.iter() {
                content.push_str("\t");
                content.push_str(hn);
            }
            content.push_str("\n");
        }
        content
    }
}

lazy_static! {
    ///
    pub static ref HOSTS_MANAGER: HostsManager = HostsManager::new();
}

/// /etc/hosts 文件节点
pub struct HostsFileNode {
    offset: Mutex<usize>,
    content: Mutex<String>,
}

impl HostsFileNode {
    ///
    pub fn new() -> Arc<Self> {
        let node = Arc::new(Self {
            offset: Mutex::new(0),
            content: Mutex::new(HOSTS_MANAGER.get_content()),
        });

        // 注册为全局文件节点
        node
    }
    #[allow(unused)]
    fn refresh_content(&self) {
        let mut content = self.content.lock();
        *content = HOSTS_MANAGER.get_content();
    }
}

impl File for HostsFileNode {
    fn readable(&self) -> bool {
        true
    }

    fn writable(&self) -> bool {
        true
    }

    fn read(&self, buf: UserBuffer) -> SyscallResult {
        let content = self.content.lock();
        let content_bytes = content.as_bytes();
        let mut offset = self.offset.lock();

        let mut total_read = 0;
        let mut current_offset = *offset;

        // 假设 buffers 是 Vec<&[u8]>，但实际需要写入，使用 unsafe 转换
        for buffer in buf.buffers.iter() {
            if current_offset >= content_bytes.len() {
                break;
            }

            let len = (buffer.len()).min(content_bytes.len() - current_offset);
            if len == 0 {
                break;
            }

            // 将不可变引用转换为可变引用（需要非常小心）
            let ptr = buffer.as_ptr() as *mut u8;

            unsafe {
                core::ptr::copy_nonoverlapping(
                    content_bytes.as_ptr().add(current_offset),
                    ptr,
                    len,
                );
            }

            current_offset += len;
            total_read += len;
        }

        *offset = current_offset;
        Ok(total_read)
    }

    fn write(&self, buf: UserBuffer) -> SyscallResult {
        let mut total_written = 0;
        let mut new_content = String::new();

        for buffer in buf.buffers.iter() {
            let data = unsafe { core::slice::from_raw_parts(buffer.as_ptr(), buffer.len()) };
            if let Ok(utf8_data) = core::str::from_utf8(data) {
                new_content.push_str(utf8_data);
                total_written += buffer.len();
            }
        }

        // 重新加载 hosts 配置
        HOSTS_MANAGER.load_from_content(&new_content);

        // 刷新文件内容
        let mut content = self.content.lock();
        *content = HOSTS_MANAGER.get_content();

        // 重置偏移量
        let mut offset = self.offset.lock();
        *offset = 0;

        Ok(total_written)
    }

    fn open(&self) -> SyscallResult {
        let mut offset = self.offset.lock();
        *offset = 0;
        Ok(0)
    }

    fn release(&self) -> SyscallResult {
        Ok(0)
    }

    fn get_stat(&self, stat: &mut Kstat) -> Result<(), SysError> {
        let content = self.content.lock();
        stat.st_ino = 2; // 固定的 inode 号
        stat.st_nlink = 1;
        stat.st_size = content.len() as i64;
        stat.st_mode = 0o644; // -rw-r--r--
        stat.st_blksize = 512;
        stat.st_blocks = (stat.st_size as u64 + 511) / 512;

        // 设置时间戳
        stat.st_atime_sec = 0;
        stat.st_atime_nsec = 0;
        stat.st_mtime_sec = 0;
        stat.st_mtime_nsec = 0;
        stat.st_ctime_sec = 0;
        stat.st_ctime_nsec = 0;

        Ok(())
    }

    fn flush(&self) {}

    fn get_fileinner(&self) -> MutexGuard<'_, FileInner> {
        // 这个方法需要根据你的 FileInner 结构实现
        // 如果不需要可以 panic 或者返回一个默认值
        panic!("HostsFileNode doesn't use FileInner")
    }
}

/// 初始化 /etc/hosts 文件系统节点
pub fn init_hosts_file() -> Arc<HostsFileNode> {
    HostsFileNode::new()
}

/// 解析主机名（供网络栈调用）
pub fn resolve_hostname(hostname: &str) -> Option<alloc::string::String> {
    // 如果是 IP 地址格式，直接返回
    if is_ip_address(hostname) {
        return Some(hostname.to_string());
    }

    // 查询 hosts 文件
    HOSTS_MANAGER.lookup(hostname)
}

fn is_ip_address(s: &str) -> bool {
    // 简单的 IPv4 检查
    let parts: Vec<&str> = s.split('.').collect();
    if parts.len() == 4 {
        let mut all_numeric = true;
        for part in parts {
            if part.parse::<u8>().is_err() {
                all_numeric = false;
                break;
            }
        }
        if all_numeric {
            return true;
        }
    }

    // 简单的 IPv6 检查（包含 :）
    if s.contains(':') {
        return true;
    }

    false
}
