[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-Clink-args=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"]

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld",
    "-Cforce-frame-pointers=yes",
    "-Ctarget-feature=-lsx,-lasx",
]

[env]
CFLAGS_riscv64gc_unknown_none_elf = "-DRING_CORE_NOSTDLIBINC"
