//! LTP testcase exec filter.
//!
//! Switch the active policy by commenting one line below.

#[allow(dead_code)]
enum LtpExecFilter {
    Blacklist(&'static [&'static str]),
    Whitelist(&'static [&'static str]),
}

const ACTIVE_LTP_EXEC_FILTER: LtpExecFilter = LtpExecFilter::Blacklist(LTP_EXEC_BLACKLIST);
// const ACTIVE_LTP_EXEC_FILTER: LtpExecFilter = LtpExecFilter::Whitelist(LTP_EXEC_WHITELIST);

const LTP_TESTCASE_BIN_PREFIXES: &[&str] =
    &["/musl/ltp/testcases/bin/", "/glibc/ltp/testcases/bin/"];

pub fn reject_reason(path: &str, case_name: &str) -> Option<&'static str> {
    if !is_ltp_testcase_bin_path(path) {
        return None;
    }

    match ACTIVE_LTP_EXEC_FILTER {
        LtpExecFilter::Blacklist(cases) if cases.contains(&case_name) => Some("blacklist"),
        LtpExecFilter::Whitelist(cases) if !cases.contains(&case_name) => Some("not in whitelist"),
        _ => None,
    }
}

fn is_ltp_testcase_bin_path(path: &str) -> bool {
    LTP_TESTCASE_BIN_PREFIXES
        .iter()
        .any(|prefix| path.starts_with(prefix))
}

#[allow(dead_code)]
pub const LTP_EXEC_BLACKLIST: &[&str] = &[
    "dirtyc0w_shmem",
    "getrlimit02",
    "cve-2017-17052",
    "data",
    "ebizzy",
    "fdatasync03",
    "float_bessel",
    "float_exp_log",
    "float_iperb",
    "float_power",
    "float_trigo",
    "fork13",
    "fork_exec_loop",
    "copy_file_range01",
    "copy_file_range02",
    "fork_procs",
    "futex_cmp_requeue01",
    "futex_cmp_requeue02",
    "futex_wait_bitset01",
    "genacos",
    "genasin",
    "genatan",
    "genatan2",
    "genceil",
    "gencos",
    "gencosh",
    "genexp",
    "genfabs",
    "genfloor",
    "genfmod",
    "genfrexp",
    "genhypot",
    "geniperb",
    "genj0",
    "genj1",
    "genldexp",
    "genlgamma",
    "genload",
    "genlog",
    "genlog10",
    "genmodf",
    "genpow",
    "genpower",
    "gensin",
    "gensinh",
    "gensqrt",
    "gentan",
    "gentanh",
    "gentrigo",
    "geny0",
    "geny1",
    "fs_fill",
    "getresuid01",
    "getresuid01_16",
    "getresuid02",
    "getresuid02_16",
    "getresuid03",
    "getresuid03_16",
    "crash02",
    "fork14",
    "epoll_wait06",
    "epoll_wait07",
    "epoll_wait05",
    "epoll-ltp",
    "cpuset01",
    "doio",
    "dma_thread_diotest",
    "cpuhotplug_report_proc_interrupts",
    "cpuhotplug_do_kcompile_loop",
    "cpuhotplug_do_spin_loop",
    "cpuhotplug_do_disk_write_loop",
    "cpufreq_boost",
    "cpuctl_test04",
    "cpuctl_test03",
    "cpuctl_test02",
    "cpuctl_test01",
    "cpuctl_fj_cpu-hog",
    "cpuctl_def_task02",
    "cpuctl_def_task03",
    "cpuctl_def_task04",
    "cgroup_regression_fork_processes",
    "cgroup_fj_proc",
    "cpuctl_def_task01",
    "bind05",
    "accept4_01",
    "fcntl37",
    "inotify11",
    "splice02",
    "fallocate05",
    "fallocate06",
    "fanotify05",
    "fsync04",
    "accept02",
];

#[allow(dead_code)]
pub const LTP_EXEC_WHITELIST: &[&str] = &[
    "abort01",//glibc 死锁
    "accept03",
    "access01",
    "access02",
    "access03",
    "access04",
    "brk01",
    "brk02",
    "chdir01",
    "clone01",
    "clone02",
    "clone03",
    "clone05",
    "clone06",
    "clone07",
    "clone08",
    "clone09",
    "clone301",
    "clone302",
    "close_range02",
    "confstr01",
    "copy_file_range03",
    "creat01",
    "creat03",
    "creat05",
    "creat08",
    "dup01",
    "dup02",
    "dup03",
    "dup04",
    "dup05",
    "dup06",
    "dup07",
    "dup201",
    "dup202",
    "dup203",
    "dup204",
    "dup205",
    "dup206",
    "dup207",
    "dup3_01",
    "dup3_02",
    "epoll_ctl01",
    "epoll_ctl02",
    "epoll_ctl03",
    "epoll_ctl04",
    "epoll_ctl05",
    "exit01",
    "exit02",
    "fallocate03",
    "fallocate04",
    "fanotify01",
    "fanotify02",
    "fanotify03",
    "fanotify04",
    "fanotify06",
    "fanotify07",
    "fanotify08",
    "fanotify09",
    "fanotify10",
    "fanotify11",//glibc
    "fanotify12",
    "fanotify13",
    "fanotify14",
    "fanotify15",
    "fanotify16",
    "fanotify17",
    "fanotify18",
    "fanotify19",
    "fanotify20",
    "fanotify21",
    "fanotify23",
    "fcntl02",
    "fcntl02_64",
    "fcntl03",
    "fcntl03_64",
    "fcntl04",
    "fcntl04_64",
    "fcntl08",
    "fcntl08_64",
    "fcntl12",
    "fcntl12_64",
    "fcntl29",
    "fcntl29_64",
    "fcntl30",
    "fcntl30_64",
    "fgetxattr01",
    "fgetxattr02",
    "fgetxattr03",
    "flistxattr01",
    "flistxattr02",
    "flistxattr03",
    "fork01",
    "fork03",
    "fork04",
    "fork07",
    "fork08",
    "fork09",
    "fork10",
    "fremovexattr01",
    "fremovexattr02",
    "fsconfig01",
    "fsconfig02",
    "fsconfig03",
    "fsetxattr01",
    "fsmount01",
    "fsmount02",
    "fsopen01",
    "fsopen02",
    "fspick01",
    "fspick02",
    "fstat02",
    "fstat02_64",
    "fstatfs01",
    "fstatfs01_64",
    "fstatfs02",
    "fstatfs02_64",
    "fsync01",
    "fsync03",
    "ftruncate01",
    "ftruncate01_64",
    "ftruncate03",
    "ftruncate03_64",
    "getcwd02",
    "getcwd03",
    "getdents01",
    "getdents02",
    "getdomainname01",
    "getegid01",
    "getegid01_16",
    "getegid02",
    "getegid02_16",
    "geteuid01",
    "geteuid02",
    "getgid01",
    "getgid03",
    "gethostname01",
    "getpagesize01",
    "getpgid01",
    "getpgid02",
    "getpgrp01",
    "getpid01",
    "getpid02",
    "getppid01",
    "getppid02",
    "gettid01",
    "gettid02",
    "getxattr01",
    "getxattr02",
    "getxattr03",
    "inotify01",
    "inotify02",
    "inotify03",
    "inotify04",
    "inotify06",
    "inotify10",
    "inotify12",
    "inotify_init1_01",
    "inotify_init1_02",
    "lgetxattr01",
    "lgetxattr02",
    "listxattr01",
    "listxattr02",
    "listxattr03",
    "llistxattr01",
    "llistxattr02",
    "llistxattr03",
    "lremovexattr01",
    "madvise01",
    "madvise02",
    "madvise05",
    "madvise10",
    "memfd_create01",
    "mlock01",
    "mlock02",
    "mlock03",
    "mlock04",
    "mlock05",
    "mmap01",
    "mmap02",
    "mmap03",
    "mmap04",
    "mmap05",
    "mmap08",
    "mmap09",
    "mmap10",
    "mmap12",
    "mmap13",
    "mmap14",
    "mmap15",
    "mmap17",
    "mmap18",
    "mmap19",
    "mmap20",
    "mmap21",
    "mmap22",
    "mmapstress01",
    "mmapstress04",
    "mount01",
    "mount02",
    "mount03",
    // "mount04",
    "mount05",
    "mount06",
    "mount07",
    "mount_setattr01",
    "move_mount01",
    "move_mount02",
    "open01",
    "open02",
    "open03",
    "open04",
    "open06",
    "open07",
    "open08",
    "open09",
    "open10",
    "open11",
    "openat01",
    "openat02",
    "openat04",
    "openat201",
    "openat202",
    "openat203",
    "open_tree01",
    "open_tree02",
    "pipe01",
    "pipe02",
    "pipe03",
    "pipe06",
    "pipe08",
    "pipe10",
    "pipe11",
    "pipe12",
    "pipe13",
    "pipe14",
    //慢，但是能跑
    // "rename01",
    // "rename03",
    // "rename04",
    // "rename05",
    // "rename06",
    // "rename07",
    // "rename08",
    // "rename09",
    // "rename10",
    // "rename12",
    // "rename13",
    "sbrk01",
    "sbrk02",
    "setxattr01",
    "setxattr02",
    "setxattr03",
    "splice01",
    "splice03",
    "splice04",
    "splice07",
    "splice09",
    "sync_file_range01",
    "wait01",
    "wait02",
    "wait401",
    "wait402",
    "wait403",
    "waitid01",
    "waitid02",
    "waitid03",
    "waitid04",
    "waitid05",
    "waitid06",
    "waitid07",
    "waitid08",
    "waitid09",
    "waitid10",
    "waitid11",
    "waitpid01",
    "waitpid03",
    "waitpid04",
    //fail
    // "waitpid06",
    // "waitpid07",
    // "waitpid08",
    // "waitpid09",
    // "waitpid10",
    // "waitpid11",
    // "waitpid12",
    // "waitpid13",
];
